module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/tests'],
  testMatch: [
    '<rootDir>/tests/**/__tests__/**/*.(ts|tsx|js)',
    '<rootDir>/tests/**/?(*.)(spec|test).(ts|tsx|js)',
  ],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/client/src/$1',
    '^@/components/(.*)$': '<rootDir>/client/src/components/$1',
    '^@/hooks/(.*)$': '<rootDir>/client/src/hooks/$1',
    '^@/lib/(.*)$': '<rootDir>/client/src/lib/$1',
    '^@/services/(.*)$': '<rootDir>/client/src/services/$1',
    '^@/shared/(.*)$': '<rootDir>/shared/$1',
    '^@/server/(.*)$': '<rootDir>/server/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  collectCoverageFrom: [
    'client/src/**/*.{ts,tsx}',
    'server/**/*.{ts,js}',
    'shared/**/*.{ts,js}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/*.config.*',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  coverageReporters: ['text', 'lcov', 'html'],
  testTimeout: 10000,
  maxWorkers: '50%',
  verbose: true,
  silent: false,
  errorOnDeprecated: true,
  clearMocks: true,
  restoreMocks: true,
};